site_name: PEKET Documentation
site_description: PyCBC Extension for Kilonova Emission Targeting
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
    - search.suggest
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo      
      accent: deep purple   
      toggle:
        icon: material/brightness-7
        name: Dark mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Command line tools:
    - gw-setup-pipeline: tools/gw-setup-pipeline.md
    - gw-search-significance: tools/gw-search-significance.md
    - kn-make-grid: tools/kn-make-grid.md
    - kn-ts-loop: tools/kn-ts-loop.md
  - Tutorials & Utilities: tutorials.md
  - Changelog: changelog.md