site_name: PEKET Documentation
site_description: PyCBC Extension for Kilonova Emission Targeting
theme:
  name: material
  logo: assets/bg_less_logo.png   
  favicon: assets/bg_less_logo.png
  features:
    - navigation.tabs
    - toc.integrate
    - to.follow
    - search.suggest
    - navigation.footer
    - content.code.copy
    - navigation.top
    - search.highlight
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo      
      accent: deep purple   
      toggle:
        icon: material/brightness-7
        name: Dark mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Command line tools:
    - gw-setup-pipeline: tools/gw-setup-pipeline.md
    - gw-search-significance: tools/gw-search-significance.md
    - kn-make-grid: tools/kn-make-grid.md
    - kn-ts-loop: tools/kn-ts-loop.md
  - Tutorials & Utilities: tutorials.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details

repo_name: NJamsin/PEKET
repo_url: https://github.com/NJamsin/PEKET

copyright: Copyright &copy; 2026 Noah Jamsin - Developed for my Master's Thesis and future research.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NJamsin
      name: Github profile
    - icon: fontawesome/solid/envelope
      link: noah.jamsin@student.uliege.be
      name: Mail me