executable     = /home/stu_jamsin/.conda/envs/fiesta/bin/gw-search-prep
arguments      = $(config) --detector-treshold 0.5
universe       = vanilla

output         = /home/stu_jamsin/master_package/test_real_data/logs/prep.out
error          = /home/stu_jamsin/master_package/test_real_data/logs/prep.err
log            = /home/stu_jamsin/master_package/test_real_data/logs/pipeline.log

environment    = "PYTHONUNBUFFERED=1"

request_cpus   = 1
request_memory = 16GB

queue
