executable     = /home/stu_jamsin/.conda/envs/fiesta/bin/gw-search-post
arguments      = $(config) --injection
universe       = vanilla

output         = /home/stu_jamsin/peket/test_injection/logs/post.out
error          = /home/stu_jamsin/peket/test_injection/logs/post.err
log            = /home/stu_jamsin/peket/test_injection/logs/pipeline.log

environment    = "PYTHONUNBUFFERED=1"

request_cpus   = 1
request_memory = 512MB

queue
