executable     = /home/stu_jamsin/.conda/envs/fiesta/bin/gw-search-prep
arguments      = $(config) --injection --detector-threshold 0.5
universe       = vanilla

output         = /home/stu_jamsin/peket/test_injection/logs/prep.out
error          = /home/stu_jamsin/peket/test_injection/logs/prep.err
log            = /home/stu_jamsin/peket/test_injection/logs/pipeline.log

environment    = "PYTHONUNBUFFERED=1"

request_cpus   = 1
request_memory = 16GB

queue
