Directory:
  BASE_DIR: master_package/test_real_data # Update this to your desired base directory for the run !!! ideally use one directory per run to avoid confusion
  run_name: test_run # A unique name for this run, used for naming outputs and logs 

KN_data:
  first_detection: '2017-08-17T13:38:40.000' # Time of the first detection in ISOT format !!! should be a str
  ra: 3.4461587900190143 # Right Ascension in radians
  dec: -0.4080838827694336 # Declination in radians
  EM_post_file: 'master_package/example_file/real_KN/Bu2019lm_posterior_samples.dat' # Path to the EM posterior samples file as given by NMMA's lightcurve-analysis (should work for other as long as the file as a timeshift column)
  RESAMP_post_file: 'master_package/example_file/real_KN/posterior_samples.dat' # Path to the RESAMP posterior samples file as given by NMMA's gwem-resampling (should work for other files as long as it has a 'chirp_mass' and 'mass_ratio' column)

GW_search:
  num_splits: 10 # Number of splits for the template bank
  window_size: 1000 # Size of the max time window in seconds